version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@angular/*"
    versions:
    - ">= 0"
  - dependency-name: "@angular-devkit/*"
    versions:
    - ">= 0"
