dist: xenial
language: node_js
node_js:
  - 12
addons:
  apt:
    packages:
      - coreutils
  chrome: stable
before_install:
  - npm i -g yarn@1
install: 
 - yarn
script:
  - yarn bootstrap:packages
  - yarn ci
before_deploy:
  - git remote set-url origin "https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git" > /dev/null 2>&1
  - git reset --hard
  - git checkout ${TRAVIS_BRANCH}
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: bash scripts/default-registry.sh
  skip_cleanup: true
  on:
    branch: auto-publish
