name: angular-builders

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}

      - uses: actions/cache@v1
        id: node-modules
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-node-modules
          restore-keys: ${{ runner.os }}-node-modules

      - uses: actions/setup-node@v1
        with:
          node-version: 12.12
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --non-interactive --no-progress

      - name: Bootstrap packages
        run: yarn bootstrap:packages

      - name: Run CI scripts
        run: yarn ci

      - name: deploy
        # Deploy only on the master branch.
        if: github.ref == 'refs/heads/master'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git reset --hard	
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          bash scripts/default-registry.sh
