name: ci

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - graduate

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' || (!contains(github.event.head_commit.message, 'ci(release)'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: true

    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache # Default cache directory for both Yarn and Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run CI scripts
        run: yarn ci

      - name: Publish to NPM
        if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
        run: |
          git reset --hard
          git pull origin master
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          if [ "${{ github.event.inputs.release_type }}" == "graduate" ]; then
            npm run graduate -- --yes
          else
            bash scripts/default-registry.sh
          fi
        env:
          NPM_CONFIG_PROVENANCE: true
