name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'ci(release)'))
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - if: (!github.event.pull_request)
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - if: github.event.pull_request
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: node-modules
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ runner.os }}-node-modules
          restore-keys: ${{ runner.os }}-node-modules

      - uses: actions/setup-node@v2
        with:
          node-version: 12.20.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --non-interactive --no-progress

      - name: Bootstrap packages
        run: yarn bootstrap:packages

      - name: Run CI scripts
        run: yarn ci

      - name: Publish to NPM
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git reset --hard	
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          bash scripts/default-registry.sh
