name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    if: (!contains(github.event.head_commit.message, 'ci(release)'))
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true

    steps:
      - if: (!github.event.pull_request)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - if: github.event.pull_request
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache # Default cache directory for both Yarn and Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run CI scripts
        run: yarn ci

      - name: Publish to NPM
        if: github.ref == 'refs/heads/master'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git reset --hard	
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          bash scripts/default-registry.sh
