name: graduate

on:
  workflow_dispatch:

jobs:
  build_and_graduate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache # Default cache directory for both Yarn and Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --immutable

      - name: Run CI scripts
        run: yarn ci

      - name: Graduate beta release to NPM
        run: |
          git reset --hard
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          npm run graduate -- --yes
        env:
          NPM_CONFIG_PROVENANCE: true
