name: graduate

on:
  workflow_dispatch:

jobs:
  build_and_graduate:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_TOKEN }}
          fetch-depth: 0

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ~/.cache # Default cache directory for both Yarn and Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v2
        with:
          node-version: 12.20.0
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn --non-interactive --no-progress --frozen-lockfile

      - name: Run CI scripts
        run: yarn ci

      - name: Graduate beta release to NPM
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git reset --hard	
          git config --global user.name ${{ secrets.GIT_USER }}
          git config --global user.email ${{ secrets.GIT_EMAIL }}
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          npm run graduate -- --yes
